development:
  adapter: postgresql
  encoding: unicode
  database: event_calendar_dev
  pool: 5
  username: event_calendar
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: event_calendar_test
  pool: 5
  username: event_calendar
  password:
